#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2013-2014 Spotify AB

# This file is part of dh-virtualenv.

# dh-virtualenv is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.

# dh-virtualenv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with dh-virtualenv. If not, see
# <http://www.gnu.org/licenses/>.

import logging
import os
import sys

# The debpython resides here
sys.path.insert(1, '/usr/share/python/')

from dh_virtualenv.build import Build
from dh_virtualenv.cmdline import get_default_parser

logging.basicConfig(format='%(levelname).1s: %(module)s:%(lineno)d: '
                    '%(message)s')
log = logging.getLogger(__name__)


def main():
    parser = get_default_parser()
    options, args = parser.parse_args()

    # TODO: Reduce redundancy with this and the Deployment.from_options
    verbose = options.verbose or os.environ.get('DH_VERBOSE') == '1'
    if verbose:
        log.setLevel(logging.DEBUG)

    log.info('Processing package...')
    build = Build.from_options(options)

    log.info('Creating virtualenv')
    build.create_virtualenv()

    log.info('Installing dependencies')
    build.install_dependencies()

    log.info('Installing package')
    build.install_package()
    if options.test:
        log.info('Running tests')
        build.run_tests()
    else:
        log.info('Skipped tests')

    log.info('dh-virtualenv_build: All done!')

if __name__ == '__main__':
    sys.exit(main() or 0)
