#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2013-2014 Spotify AB

# This file is part of dh-virtualenv.

# dh-virtualenv is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.

# dh-virtualenv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with dh-virtualenv. If not, see
# <http://www.gnu.org/licenses/>.

import os
import shutil

from dh_virtualenv.build import DEFAULT_BUILD_DIR
from dh_virtualenv.cmdline import DebhelperOptionParser

if __name__ == '__main__':
    usage = '%prog [options]'
    parser = DebhelperOptionParser(usage, version='%prog 0.7')
    parser.add_option('-B', '--builddirectory', dest='build_dir',
                      default=DEFAULT_BUILD_DIR, help='Build dir')
    options, args = parser.parse_args()

    if os.path.exists(build_dir):
        shutil.rmtree(build_dir, ignore_errors=True)
